FROM ubuntu:20.04

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt -y install \
               g++-8 g++-9 g++-10 \
               clang-7 clang-8 clang-9 clang-10 clang-11 clang-12 \
               cmake ninja-build ccache \
               python3 python3-dev python3-pip\
               gsl-bin libgsl-dev \
               libboost-all-dev \
               libgtk-3-dev \
               libfl-dev \
               libxml2 libxml2-dev \
               libopenmpi-dev openmpi-bin openmpi-common openmpi-doc ssh\
               libsqlite3-dev sqlite3 \
               libeigen3-dev \
               qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools \
               && python3 -m pip install cppyy==2.4.2 matplotlib numpy
